server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:mysql://${DB_URL}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2KB
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}   # use app password for Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000          # 1 hour access token
    refresh-expiration-ms: 1209600000 # 14 days refresh

# CORS config moved to SecurityConfig.corsConfigurationSource()
#cors:
#  allowed-origins:
#    - ${CORS_ALLOWED_ORGINS}

cloudflare:
  r2:
    bucket: ${CLOUDFLARE_BUCKET}
    account-id: ${CLOUDFLARE_ACCOUNT_ID}
    access-key: ${CLOUDFLARE_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_SECRET_KEY}
    endpoint: ${CLOUDFLARE_ENDPOINT} # MDU clg
